/**
 * OrderZap v2 - Automated Bootstrapper
 * 
 * This script runs across all platforms once Node.js is installed.
 * It prepares the .env files, runs package installations, and boots Docker.
 */
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');

// ── Helpers ────────────────────────────────────────────────────────
function log(msg)     { console.log(`\n\x1b[36m➤ ${msg}\x1b[0m`); }
function success(msg) { console.log(`\x1b[32m✔ ${msg}\x1b[0m`); }
function error(msg)   { console.error(`\n\x1b[31m✖ ${msg}\x1b[0m`); process.exit(1); }

function runCmd(cmd, args, cwd = ROOT) {
  const result = spawnSync(cmd, args, { cwd, shell: true, stdio: 'inherit' });
  if (result.status !== 0) {
    error(`Command failed: ${cmd} ${args.join(' ')}`);
  }
}

// ── 1. Create .env if missing ──────────────────────────────────────
log('Checking environment configuration...');
const envPath = path.join(ROOT, '.env');
const envExamplePath = path.join(ROOT, '.env.example');

let envContent = '';
if (!fs.existsSync(envPath)) {
  if (fs.existsSync(envExamplePath)) {
    envContent = fs.readFileSync(envExamplePath, 'utf8');
    
    // Inject a secure random password for Postgres if it's the default
    const securePw = crypto.randomBytes(16).toString('hex');
    envContent += `\n# Generated by setup.js\nPOSTGRES_PASSWORD=${securePw}\n`;
    
    fs.writeFileSync(envPath, envContent);
    success('Created .env from .env.example with secure database password');
  } else {
    // Basic fallback if even .env.example is missing
    const securePw = crypto.randomBytes(16).toString('hex');
    envContent = `POSTGRES_USER=postgres\nPOSTGRES_PASSWORD=${securePw}\nPOSTGRES_DB=OZ-T\nPORT=4000\n`;
    fs.writeFileSync(envPath, envContent);
    success('Generated base .env file');
  }
} else {
  success('.env already exists');
}

// ── 2. Install NPM dependencies ────────────────────────────────────
log('Installing root dependencies...');
runCmd('npm', ['install']);
success('Root dependencies installed');

const dirsToInstall = ['express', 'oz-monitor'];
for (const dir of dirsToInstall) {
  const fullPath = path.join(ROOT, dir);
  if (fs.existsSync(path.join(fullPath, 'package.json'))) {
    log(`Installing dependencies in ${dir}...`);
    runCmd('npm', ['install'], fullPath);
  }
}
success('All sub-project dependencies installed');

// ── 3. Start Infrastructure (Docker) ───────────────────────────────
log('Starting Docker infrastructure (PostgreSQL 18 + Convex)...');
runCmd('docker', ['compose', 'up', '-d']);
success('Database and Backend infrastructure is up');

// ── 4. Verify Convex & Database ────────────────────────────────────
log('Waiting for infrastructure health...');
// Give it a moment to boot
runCmd('node', ['-e', '"setTimeout(String,5000)"']);

console.log('\n\x1b[32m===================================================\x1b[0m');
console.log('\x1b[32m✔ OrderZap installation complete!\x1b[0m');
console.log('\x1b[32m===================================================\x1b[0m\n');
log('Booting OrderZap Monitor automatically...');
const monitorPath = path.join(ROOT, 'oz-monitor');
runCmd('npm', ['start'], monitorPath);
