import { ConvexHttpClient } from "convex/browser";
import "dotenv/config";

/**
 * convex.ts — Convex HTTP Client Configuration
 * ──────────────────────────────────────────
 * This client is used by the Express API to trigger real-time mutations
 * after successful PostgreSQL persistence (The "Mirror" update).
 */

const CONVEX_URL = process.env.CONVEX_URL || "http://127.0.0.1:3210";

if (!CONVEX_URL) {
  console.warn("⚠️  CONVEX_URL is not set. Real-time sync will be disabled.");
}

export const convex = new ConvexHttpClient(CONVEX_URL);

/**
 * Sync an order to Convex.
 * This is a helper to trigger the internal mutation.
 */
export async function syncOrderToConvex(pgOrder: any, items: any[]) {
  try {
    // We call the internal mutation defined in convex/orders.ts
    // Note: We need to ensure the mutation is exported as 'internal' or use a public wrapper.
    // In this case, we'll use the 'insertOrderMirror' mutation.
    
    // Mapping PostgreSQL fields to Convex expected fields
    const convexPayload = {
      pg_id: pgOrder.id.toString(), // Ensure string for UUID
      table_no: pgOrder.table_number || 0,
      items: items.map(item => item.name),
      total: parseFloat(pgOrder.total_amount),
      status: mapStatusToConvex(pgOrder.status),
    };

    // @ts-ignore - 'api' is generated by Convex but we can reference internal strings
    await convex.mutation("orders:insertOrderMirror", convexPayload);
    return true;
  } catch (err) {
    console.error("❌ Convex Sync Failed for Order:", pgOrder.id, err);
    return false;
  }
}

function mapStatusToConvex(status: string): string {
  const map: Record<string, string> = {
    "pending": "pending",
    "preparing": "cooking",
    "ready": "served", // Assuming served means ready/served in the legacy mirror
    "completed": "served",
    "cancelled": "served", // Basic mapping for now
  };
  return map[status] || "pending";
}

export default convex;
